# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/42jerrykim"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:42jerrykim@gmail.com"

[social.params]
icon = "envelope-regular"

[[social]]
identifier = "kakao"
name = "Kakao"
url = "https://open.kakao.com/o/s5FFkQWg"

[social.params]
icon = "kakao"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
