# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JerryKim
email: 42jerrykim@gmail.com
description: Jerry Kim의 개발 블로그입니다.
github_username: 42jerrykim
minimal_mistakes_skin: dark

search: true
search_provider: google
google:
  search_engine_id: 377f46c571dd54b13
  instant_search: true
repository               : "42jerrykim/42jerrykim.github.io"

# logo: /assets/images/undefined/KakaoTalk_20220210_094951700.png
logo: https://upload.wikimedia.org/wikipedia/commons/5/56/Answer_to_Life.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

enable_copy_code_button: true

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul

breadcrumbs: true  # disabled by default
collections_dir: articles

# naver_site_verification: "4b02ffa47d254e19822fdb25d0655a823faf52f3"
google-site-verification: googleb84d4a34dffafade.html


teaser: https://pilbox.themuse.com/image.jpg?filter=antialias&h=422&opt=1&pos=top-left&prog=1&q=keep&url=https%3A%2F%2Fcms-assets.themuse.com%2Fmedia%2Flead%2F01212022-1047259374-coding-classes_scanrail.jpg%3Fv%3D1cc61016a54a7e07475549aca7c39b38545e3ed6&w=767
og_image: /assets/images/undefined/KakaoTalk_20220210_094951700.png

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  
author:
  name   : "Jerry Kim"
  avatar : "/assets/images/undefined/KakaoTalk_20220210_095101080.png"
  bio    : "[42](https://simple.wikipedia.org/wiki/42_(answer))는 'The Hitchhiker's Guide to the Galaxy'라는 SF 소설에서 삶, 우주, 그리고 모든 것에 대한 궁극적인 질문에 대한 해답이다."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/42jerrykim/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/42jerrykim/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/42jerrykim/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/42jerrykim/"
    - label: "Mail"
      icon: "fa-regular fa-envelope"
      url: "mailto:42jerrykim@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _bashshell
  - scope:
      path: ""
      type: bashshell
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _cycle
  - scope:
      path: ""
      type: cycle
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  #_designpattern
  - scope:
      path: ""
      type: designpattern
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  #_baekjoon
  - scope:
      path: ""
      type: baekjoon
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _cleanarchitecture
  - scope:
      path: ""
      type: cleanarchitecture
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _algorithm
  - scope:
      path: ""
      type: algorithm
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _testing
  - scope:
      path: ""
      type: testing
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _cmd
  - scope:
      path: ""
      type: cmd
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _unittesting
  - scope:
      path: ""
      type: unittesting
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _computerterms
  - scope:
      path: ""
      type: computerterms
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _pythoncheatsheet
  - scope:
      path: ""
      type: pythoncheatsheet
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true
  # _rust
  - scope:
      path: ""
      type: rust
    values:
      layout: single
      author_profile: true
      share: true
      toc: true  
      toc_sticky: true
      toc_icon: "align-left"
      comments: true
      read_time: true
      show_date: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  bashshell:
    Title: "Bash Shell"
    output: true
    permalink: /collections/:collection/:path/
  testing:
    Title: "Testing"
    output: true
    permalink: /collections/:collection/:path/
  cycle:
    Title: "Cycle"
    output: true
    permalink: /collections/:collection/:path/
  designpattern:
    Title: "Design Pattern"
    output: true
    permalink: /collections/:collection/:path/
  algorithm:
    Title: "Algorithm"
    output: true
    permalink: /collections/:collection/:path/
  cmd:
    Title: "CMD"
    output: true
    permalink: /collections/:collection/:path/
  cleanarchitecture:
    Title: "Clean Architecture"
    output: true
    permalink: /collections/:collection/:path/
  unittesting:
    Title: "Unit Testing"
    output: true
    permalink: /collections/:collection/:path/
  computerterms:
    Title: "컴퓨터 용어집"
    output: true
    permalink: /collections/:collection/:path/
  baekjoon:
    Title: "백준"
    output: true
    permalink: /collections/:collection/:path/
  pythoncheatsheet:
    Title: "Python Cheat Sheet"
    output: true
    permalink: /collections/:collection/:path/
  rust:
    Title: "Rust"
    output: true
    permalink: /collections/:collection/:path/


comments:
  provider: "utterances"
  utterances:
    theme                : photon-dark
    issue_term           : pathname
    label                : BlodComment

# compress_html:
#   clippings: all
#   ignore:
#     envs: development  # disable compression in dev environment
