name: Generate plantuml
on:
  push:
    branches: ["main"]

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@master
        with:
          path: plantuml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}